### ISSUE TITLE
CVE-2017–13156

### ISSUE THREAD

**Issue by MixColumns** [astarub/campus_app#120]
The APK from Playstore is signed with v1 signature and if Android version is < 7.0 (API Level <24) there might be a vulnurability. Since v2 signatures are only supported on 7.0 upwards malicous code can be injected into the app without invalidating the v1 signature. An attacker could inject DEX code at the unsigned beginning of the APK. This should work on Android 5.0 to 7.0 even though a v2 signature is present.

See:
https://nvd.nist.gov/vuln/detail/CVE-2017-13156
https://mobile-security.gitbook.io/mobile-security-testing-guide/android-testing-guide/0x05a-platform-overview#apk-signing-schemes

**Comment by henry-herrmann** [comment]
Will be fixed with #114.

**Comment by domai-tb** [comment]
Thank you for reporting this vulnerability. Nevertheless, we would ask you to adhere to our [security guidelines](https://github.com/astarub/campus_app/security) next time. Vulnerabilities should not be reported publicly until they have been fixed.

**Comment by MixColumns** [comment]
Well your policie states [...] avoid revealing information about vulnerabilities in public **if that could put users at risk**.

I dont think that this is currently the case. The App already got released with those settings and a major update is planned. The APK is already out there with the signing as it is. If you want the GitHub-Security-Advisory to be used you should also rephrase the wording. For example change "please use" to "must use". Make it more clear how you want to have it reported.

**Comment by domai-tb** [comment]
Then I'm sorry, I assumed that an already known vulnerability with a CVSS of category High would be enough to recognize that there is a risk for users. Especially if the current release is prone to vulnerabilities, a Responsible Disclosure should be triggered instead of publicly disclosing them directly.

Don't get me wrong, of course we can't force you to use the GitHub Security Advisory, but publishing an existing and currently exploitable vulnerability without a prior responsible disclosure process does put users at risk.

**Comment by MixColumns** [comment]
@henry-herrmann i think v1 signature is still in use. It would be good to disable it completely imo
