### ISSUE TITLE
BottomNavMenu looses transparency after first navigation

### ISSUE THREAD

**Issue by C4s4r** [astarub/campus_app#16]
Normally, the BottomNavMenu has a transparent background with a shadow effect.
At first, this works fine. But when the user interacts with the BottomNavMenu and navigates to a different page, the transparency is replaced with a white background.

![transparency-gone-bottomnavmenu](https://user-images.githubusercontent.com/56138477/192744013-61d82e69-1901-4ae3-b56f-1069ed353ce2.png)

**Comment by henry-herrmann** [comment]
It appears that this is caused by the exit animation triggered when navigating to a different page. 

Removing the function calls of the exit animation in lib/pages/home/home_page.dart results in maintaing the transparent background. 

It is yet unknown what component of the exit animation is causing the issue.
